from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Callable

from rich import box
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from soul import db
from soul.bootstrap import validate_startup
from soul.config import Settings, clear_settings_cache, get_settings
from soul.core.soul_loader import Soul, load_soul
from soul.core.timezone_utils import load_timezone


def mkdir_secure(path: Path) -> None:
    """Create a directory with owner-only permissions when supported."""
    path.mkdir(parents=True, exist_ok=True)
    try:
        path.chmod(0o700)
    except OSError:
        pass


def write_secure(path: Path, content: str) -> None:
    """Write sensitive files with owner-only permissions when supported."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass


def ensure_runtime_files(settings: Settings) -> None:
    mkdir_secure(settings.soul_data_dir)
    if settings.database_is_sqlite:
        mkdir_secure(settings.sqlite_path.parent)
    mkdir_secure(settings.session_log_dir)
    mkdir_secure(settings.session_archive_dir)
    mkdir_secure(settings.exports_dir)
    mkdir_secure(settings.temp_dir)

    if not settings.soul_file.exists():
        write_secure(settings.soul_file, settings.default_soul_yaml)
        try:
            settings.soul_file.chmod(0o600)
        except OSError:
            pass


def bootstrap(*, ensure_runtime_files_func: Callable[[Settings], None] = ensure_runtime_files) -> tuple[Settings, Soul]:
    settings = get_settings()
    ensure_runtime_files_func(settings)
    validate_startup(settings)
    soul = load_soul(settings.soul_file)
    return settings, soul


def local_timezone_name(default: str = "UTC") -> str:
    candidates = [
        getattr(datetime.now().astimezone().tzinfo, "key", None),
        str(datetime.now().astimezone().tzinfo or "").strip(),
        default,
    ]
    for candidate in candidates:
        if not candidate:
            continue
        try:
            load_timezone(candidate)
        except Exception:
            continue
        return candidate
    return default


def prompt_text(
    console: Console,
    ask: Callable[..., str],
    label: str,
    *,
    default: str | None = None,
    required: bool = False,
) -> str:
    while True:
        prompt_kwargs: dict[str, object] = {}
        if default not in {None, ""}:
            prompt_kwargs["default"] = default
        value = ask(label, **prompt_kwargs).strip()
        if value:
            return value
        if default not in {None, ""}:
            return str(default).strip()
        if not required:
            return ""
        console.print("[red]This value is required.[/red]")


def prompt_secret(
    console: Console,
    ask: Callable[..., str],
    label: str,
    *,
    existing: str | None = None,
    required: bool = False,
) -> str:
    prompt_label = f"{label} (leave blank to keep current)" if existing else label
    while True:
        value = ask(prompt_label, password=True, default="").strip()
        if value:
            return value
        if existing:
            return existing
        if not required:
            return ""
        console.print("[red]This value is required.[/red]")


def prompt_timezone(
    console: Console,
    default: str,
    *,
    prompt_text_func: Callable[..., str],
) -> str:
    while True:
        candidate = prompt_text_func("Timezone", default=default, required=True)
        try:
            load_timezone(candidate)
        except Exception:
            console.print(f"[red]Invalid timezone:[/red] {candidate}")
            console.print("[dim]Use an IANA timezone like UTC, Asia/Kolkata, or America/New_York.[/dim]")
            continue
        return candidate


def prompt_int(
    console: Console,
    label: str,
    *,
    default: str | None = None,
    prompt_text_func: Callable[..., str],
) -> str:
    while True:
        candidate = prompt_text_func(label, default=default, required=True)
        try:
            int(candidate)
        except ValueError:
            console.print(f"[red]{label} must be an integer.[/red]")
            continue
        return candidate


def serialize_env_value(value: str | bool | int | float) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return json.dumps(value, ensure_ascii=True)


def render_env_content(values: dict[str, str | bool | int | float]) -> str:
    lines = [
        "# Generated by `soul init`.",
        "# Review this file any time with `soul config`.",
        "",
        "# Core provider",
        f"OPENAI_API_KEY={serialize_env_value(values['OPENAI_API_KEY'])}",
    ]
    if values.get("OPENAI_BASE_URL"):
        lines.append(f"OPENAI_BASE_URL={serialize_env_value(str(values['OPENAI_BASE_URL']))}")
    lines.extend(
        [
            f"LLM_MODEL={serialize_env_value(str(values['LLM_MODEL']))}",
            f"MOOD_OPENAI_MODEL={serialize_env_value(str(values['MOOD_OPENAI_MODEL']))}",
            "",
            "# Storage and runtime",
            f"SOUL_DATA_DIR={serialize_env_value(str(values['SOUL_DATA_DIR']))}",
            f"SOUL_USER_ID={serialize_env_value(str(values['SOUL_USER_ID']))}",
            f"SOUL_TIMEZONE={serialize_env_value(str(values['SOUL_TIMEZONE']))}",
            f"ENVIRONMENT={serialize_env_value(str(values['ENVIRONMENT']))}",
            "",
            "# Optional features",
            f"ENABLE_VOICE={serialize_env_value(bool(values['ENABLE_VOICE']))}",
        ]
    )
    if values.get("ELEVENLABS_API_KEY"):
        lines.append(f"ELEVENLABS_API_KEY={serialize_env_value(str(values['ELEVENLABS_API_KEY']))}")
    if values.get("ELEVENLABS_VOICE_ID"):
        lines.append(f"ELEVENLABS_VOICE_ID={serialize_env_value(str(values['ELEVENLABS_VOICE_ID']))}")
    lines.append(f"ENABLE_TELEGRAM={serialize_env_value(bool(values['ENABLE_TELEGRAM']))}")
    if values.get("TELEGRAM_BOT_TOKEN"):
        lines.append(f"TELEGRAM_BOT_TOKEN={serialize_env_value(str(values['TELEGRAM_BOT_TOKEN']))}")
    if values.get("TELEGRAM_CHAT_ID"):
        lines.append(f"TELEGRAM_CHAT_ID={serialize_env_value(str(values['TELEGRAM_CHAT_ID']))}")
    lines.extend(
        [
            "",
            "# Local services",
            f"ENABLE_PROACTIVE={serialize_env_value(bool(values['ENABLE_PROACTIVE']))}",
            f"ENABLE_REFLECTION={serialize_env_value(bool(values['ENABLE_REFLECTION']))}",
            f"ENABLE_DRIFT={serialize_env_value(bool(values['ENABLE_DRIFT']))}",
            f"ENABLE_BACKGROUND_JOBS={serialize_env_value(bool(values['ENABLE_BACKGROUND_JOBS']))}",
        ]
    )
    return "\n".join(lines) + "\n"


def settings_for_init(env_file: Path) -> Settings:
    if env_file.exists():
        return Settings(_env_file=str(env_file))
    return Settings(_env_file=None)


def run_init_command(
    *,
    console: Console,
    env_file: Path,
    force: bool,
    confirm_ask: Callable[..., bool],
    prompt_text_func: Callable[..., str],
    prompt_secret_func: Callable[..., str],
    prompt_timezone_func: Callable[[str], str],
    prompt_int_func: Callable[..., str],
) -> None:
    env_file = env_file.resolve()
    existing = settings_for_init(env_file)

    if env_file.exists() and not force:
        overwrite = confirm_ask(
            f"{env_file} already exists. Overwrite it with a new guided config?",
            default=False,
        )
        if not overwrite:
            console.print("[dim]Cancelled.[/dim]")
            return

    console.print(
        Panel(
            "Answer a few questions and SOUL will write a local `.env`, create `soul_data/`, and initialize SQLite.",
            title="SOUL Init",
            box=box.SIMPLE,
            border_style="magenta",
        )
    )

    openai_api_key = prompt_secret_func(
        "OpenAI API key",
        existing=existing.openai_api_key.get_secret_value() if existing.openai_api_key else None,
        required=True,
    )
    openai_base_url = prompt_text_func(
        "OpenAI-compatible base URL (optional)",
        default=existing.openai_base_url,
    )
    llm_model = prompt_text_func("Chat model", default=existing.llm_model, required=True)
    mood_model = prompt_text_func("Mood model", default=existing.mood_openai_model, required=True)
    soul_data_dir = prompt_text_func("SOUL data directory", default=existing.soul_data_path, required=True)
    timezone_default = existing.timezone_name
    if not env_file.exists() and timezone_default == Settings.model_fields["timezone_name"].default:
        timezone_default = local_timezone_name(timezone_default)
    timezone_name = prompt_timezone_func(timezone_default)

    enable_voice = confirm_ask("Enable voice support?", default=existing.enable_voice)
    elevenlabs_api_key = ""
    elevenlabs_voice_id = ""
    if enable_voice:
        elevenlabs_api_key = prompt_secret_func(
            "ElevenLabs API key",
            existing=existing.elevenlabs_api_key.get_secret_value() if existing.elevenlabs_api_key else None,
            required=True,
        )
        elevenlabs_voice_id = prompt_text_func(
            "ElevenLabs voice ID",
            default=existing.elevenlabs_voice_id,
            required=True,
        )

    enable_telegram = confirm_ask("Enable Telegram bot support?", default=existing.enable_telegram)
    telegram_bot_token = ""
    telegram_chat_id = ""
    if enable_telegram:
        telegram_bot_token = prompt_secret_func(
            "Telegram bot token",
            existing=existing.telegram_bot_token.get_secret_value() if existing.telegram_bot_token else None,
            required=True,
        )
        telegram_chat_id = prompt_int_func("Telegram chat ID", default=existing.telegram_chat_id)

    env_values: dict[str, str | bool | int | float] = {
        "OPENAI_API_KEY": openai_api_key,
        "LLM_MODEL": llm_model,
        "MOOD_OPENAI_MODEL": mood_model,
        "SOUL_DATA_DIR": soul_data_dir,
        "SOUL_USER_ID": existing.user_id,
        "SOUL_TIMEZONE": timezone_name,
        "ENVIRONMENT": existing.environment or "development",
        "ENABLE_VOICE": enable_voice,
        "ENABLE_TELEGRAM": enable_telegram,
        "ENABLE_PROACTIVE": existing.enable_proactive,
        "ENABLE_REFLECTION": existing.enable_reflection,
        "ENABLE_DRIFT": existing.enable_drift,
        "ENABLE_BACKGROUND_JOBS": existing.enable_background_jobs,
    }
    if openai_base_url:
        env_values["OPENAI_BASE_URL"] = openai_base_url
    if elevenlabs_api_key:
        env_values["ELEVENLABS_API_KEY"] = elevenlabs_api_key
    if elevenlabs_voice_id:
        env_values["ELEVENLABS_VOICE_ID"] = elevenlabs_voice_id
    if telegram_bot_token:
        env_values["TELEGRAM_BOT_TOKEN"] = telegram_bot_token
    if telegram_chat_id:
        env_values["TELEGRAM_CHAT_ID"] = telegram_chat_id

    write_secure(env_file, render_env_content(env_values))
    clear_settings_cache()

    settings = Settings(_env_file=str(env_file))
    ensure_runtime_files(settings)
    db.init_db(settings.database_url)

    table = Table(title="SOUL Init Complete", box=box.SIMPLE_HEAVY, show_header=False)
    table.add_column("Field", style="magenta", width=18)
    table.add_column("Value", style="white")
    table.add_row("Config", str(env_file))
    table.add_row("Data dir", str(settings.soul_data_dir))
    table.add_row("Database", settings.redacted_database_url)
    table.add_row("Timezone", settings.timezone_name)
    console.print(table)
    console.print("[green]Run `soul chat` to start talking, or `soul config` to inspect the resolved settings.[/green]")
    if enable_voice:
        console.print("[dim]Voice support also needs the voice extras installed before `soul chat --voice` will work.[/dim]")
    if enable_telegram:
        console.print("[dim]Telegram support is configured, but the bot will only start when you run `soul telegram-bot`.[/dim]")

